/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tianscar_soundtouch4j_BPMDetector */

#ifndef _Included_com_tianscar_soundtouch4j_BPMDetector
#define _Included_com_tianscar_soundtouch4j_BPMDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tianscar_soundtouch4j_BPMDetector
 * Method:    createInstance
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_tianscar_soundtouch4j_BPMDetector_createInstance
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_tianscar_soundtouch4j_BPMDetector
 * Method:    destroyInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tianscar_soundtouch4j_BPMDetector_destroyInstance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tianscar_soundtouch4j_BPMDetector
 * Method:    putSamples
 * Signature: (J[FI)V
 */
JNIEXPORT void JNICALL Java_com_tianscar_soundtouch4j_BPMDetector_putSamples
  (JNIEnv *, jclass, jlong, jfloatArray, jint);

/*
 * Class:     com_tianscar_soundtouch4j_BPMDetector
 * Method:    putSamples_i16
 * Signature: (J[SI)V
 */
JNIEXPORT void JNICALL Java_com_tianscar_soundtouch4j_BPMDetector_putSamples_1i16
  (JNIEnv *, jclass, jlong, jshortArray, jint);

/*
 * Class:     com_tianscar_soundtouch4j_BPMDetector
 * Method:    getBpm
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_tianscar_soundtouch4j_BPMDetector_getBpm
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
