/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tianscar_soundtouch4j_SoundTouch */

#ifndef _Included_com_tianscar_soundtouch4j_SoundTouch
#define _Included_com_tianscar_soundtouch4j_SoundTouch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tianscar_soundtouch4j_SoundTouch
 * Method:    createInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tianscar_soundtouch4j_SoundTouch_createInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_tianscar_soundtouch4j_SoundTouch
 * Method:    destroyInstance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_tianscar_soundtouch4j_SoundTouch_destroyInstance
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
